export const VALUES_AND_INTERVAL = [
  'returnsBTC',
  'volaBTC',
  'volaETH',
  'txncostETH',
  'returnsBNB',
  'returnsADA',
  'cashvolADA',
  'returnsETC',
  'volaETC',
  'cashvolETH',
  'cashvolLTC',
  'cashvolLINK',
  'volaADA',
  'returnsLINK',
  'cashvolETC',
  'volaLTC',
  'volaLINK',
  'returnsLTC',
  'cashvolBTC',
  'returnsETH',
  'volaBNB',
  'cashvolBNB',
];

export const STATUS_COLOR: { [key: string]: string } = {
  Allowed: '#1CC272',
  Waiting: '#FABE23',
  Refused: '#FD686A',
};
